- app/scripts/apps/notes/show/templates/item.html
The previous styling of the "Notebook" name in "Note" preview view looks like this:
My notebook "Essays" was so faint and blended in I almost thought it was part of my note. My proposed solution in this pull request looks like this:
Hopefully y'all like my idea. I believe it better separates the notebook from the UI, it was a bit blending together IMHO... now I think it is more clearly a "UI" element
> added icon & seperator line to Notebook name in Note preview

- app/locales/es/translation.json
Replaced Superiro with Superior.
> Fixed typo on Spanish translation.

- app/scripts/apps/notes/appNote.js
- app/scripts/apps/notes/form/controller.js
If the user has filtered the sidebar by a notebook before they click the
new note button, the notebook is selected by default for the note.
The filter and query are included in the URI for the `notes/add` route.
The note form will use these two values to figure out which notebook to
pre-select in case the currently edited note doesn't have a notebook
assigned.
Implements #271
> Use previously selected notebook for a new note

- app/scripts/apps/notebooks/appNotebooks.js
- app/scripts/apps/notebooks/form/notebook/controller.js
- app/scripts/apps/notes/form/views/notebooks.js
When the user adds a new notebook while creating/editing an existing
note, the notebook is selected automatically.
The implementation is done by returning a promise from the `appNotebook` `show:form` reply. This promise is passed on to the `form/notebook/app` which resolved it with the new notebook during save or with null value `onDestroy` if it hasn't been resolved previously.
I opted for promises to better target the result as a global request/reply might have changed the drop down notebook value in cases where the user wasn't adding a new notebook through the drop down. Promises guarantee that only notebook forms requested by the notebook view may alter the selected item of the said view.
> Select the newly added notebook in notes form

- app/index.html
Note: Windows caches the tile icons very aggressively. The easiest way to test the effectiveness of this change is to open Laverna with URL such as `http://localhost:9000/?` - the `?` makes Windows consider it a different page and bypasses the cache (once).
Pinning itself can be done in for Edge using "Pin to Start" found in the menu for example.
Fixes #240
> Fix Windows tile image paths in index.html

- README.md
Added `(cd test && bower install)` as a necessary command.
`gulp build` fails otherwise, since it attempts to run mocha tests.
> update README for installation from source

- package.json
Without this, one can package the app with electron successfully - but this app cannot open links (Ugly error message appears instead)
> Add runtime dependency for the desktop app that is required to open links

- electron.js
- gulpfile.js
- package.json
- preload.js
- Added a `preload.js` script that runs on every `BrowserWindow` for `Electron` compatibility with `RequireJS`
- `Electron` dev tool and a `--dev` flag for unminimised `Gulp` builds
> Preload to prevent breaking external pages in Electron. Fixes #328, #351

- app/scripts/apps/navbar/show/template.html
- app/scripts/apps/settings/sidebar/templates/navbar.html
- app/styles/core/header.less
- app/styles/theme-default/header.less
Covers secondary issues brought up in #305, along with some code cleanup.
> Fix padding around header title text

- app/styles/theme-default/prism.less
Inline code blocks were receiving the same style as code fences, thus
showing up on a new line.
Also, some duplicate (conflicting) CSS was removed/merged together.
Fixes #362
**Result**:
> :bug: fix inline code blocks not showing up inline

- app/styles/theme-default/prism.less
- Fixes overflow on Firefox
- Fixes inline code blocks to match with Coy theme (red text, border, padding, etc)
- Fixes right border not appearing
**before**:
**after**:
> :bug: fix Coy theme for Prism

- app/locales/lv/translation.json
Changes:
* Nejaušs -> nejauša. It clearly applies to "sāls" in the UI and therefore this form is correct.
* One typo.
* Some grammar / phrasing.
> Update the Latvian locale - fix a typo and some grammar.

- app/scripts/apps/notes/show/controller.js
- app/scripts/modules/remotestorage/classes/sync.js
Hi! I've seen that you've referenced a commit on my issue, so I've decided to give it a try and unfortunately, this wasn't still working. So I've decided to be brave and to contribute a bit.
There were two issues with the RemoteStorage module: on the local version, `model.updated` is actually undefined, triggering updates all the time. `model.attributes.updated` is the actual value to check, for the local model. To make it clear which is the local model vs which is the remote one, I've renamed them `lmodel` (resp. `rmodel`) for the local (resp. remote) model.
The second issue was that there was a missing check for remote-to-local sync (if the note has been remotely updated but not locally). I just got inspired from the Dropbox sync. Maybe it'd be worth it to make these checks abstract …
> Fix RemoteStorage support

- app/scripts/apps/navbar/show/template.html
Change the label to make it a bit more usable, because that’s what it
actually shows.
> Sidemenu: now "Notebooks & tags"

- app/scripts/apps/navbar/show/template.html
Not clear in navbar where to find tags. Possibly should break tags into separate item later?
> Add tag location

- .travis.yml
Latest versions of electron use node 6.
> Added travis ci support for node 6

- README.md
The following changes are in response to #504: 
**Changes:** 
-  added caveat for installing "bower" and "gulp" globally
- added the command for starting Laverna
@wwebfor Since ```gulp``` is used to start the program, I think ```"start:" "node ./server.js",``` should reflect this in the ```package.json``` file.
> Updated "Installation from Source" in Readme.md

- app/scripts/apps/settings/sidebar/template.html
Fixes #510
Instead of always loading "Other" in the sidebar of settings for every language, the translation for "Other" is looked up in the translation file.
> "Other" not any more hard coded into sidebar template

- app/locales/de/translation.json
- app/locales/en/translation.json
- app/locales/ru/translation.json
- app/locales/tr/translation.json
- app/scripts/apps/settings/show/templates/profiles.html
Now the "profile name" string will be translated. Although the i18n mark
was set in the profiles.html, the "Profile name" was missing in the
translation files. So I changed the i18n call to 'profile.profile name',
updated the translation in the Russian and Turkish translation and added
the translation to the English and German file.
> Translate profile name in Settings->Profile

- app/locales/ar/translation.json
- app/locales/da/translation.json
- app/locales/de/translation.json
- app/locales/en/translation.json
- app/locales/fr/translation.json
- app/locales/ko/translation.json
- app/locales/lt/translation.json
- app/locales/lv/translation.json
- app/locales/sq/translation.json
- app/scripts/apps/notes/form/controller.js
- app/scripts/apps/settings/controller.js
The "You have unsaved changes." sentence in the cancel dialog was never translated. This was due to the dot in the sentence in the translation files. In JSON files, this dot is a call for a subclass, not the end of a sentence. Because of that, the translation was never found. I deleted the dot in the files where a new cancel dialog is created and in all translation files.
> Fix a translation bug with "You have unsaved changes."

- app/scripts/apps/notes/form/controller.js
- app/scripts/apps/notes/remove/controller.js
Cancel Button in editing mode doesn't saves the changes any more. This bug happend due to the autosave feature, which automatically saves changes without asking. This bug was solved by saving the unchanged note in the variable "dataBeforeChange" before any change was made. When you now cancel editing, this data will override the autosaved note. When you cancel editing a new note, it will be deleted. If your computer crashes while editing, the autosaved note will still be there, so nothing is lost.
> Cancel doesn't save changes any more

- package.json
The package.json was missing a dependency to the `dev-ip` module, which caused the `gulp build` command to fail. This commit fixes that issue.
> Add missing dependency to dev-ip

- app/scripts/modules/markdown/libs/markdown-it.js
Fixes #491
You can now use Unicode characters in tags. I used a code snippet that
the creator of the markdown-it-hashtag created exactly for this problem
( https://github.com/svbergerem/markdown-it-hashtag/blob/master/test/hashtag.js#L23-L27 ). I modified it to use \u (four hexadecimal digits) instead of \x (two hexadecimal digits), so that you can use all of the Unicode symbols.
> Allow Unicode in tags

- app/scripts/apps/notes/form/controller.js
I fixed this bug before( #532 ), but somehow another commit overwrote the
deletion of the point in the notes form controller. I commit this one
little change again.
> Fix point in "unsaved data" dialog again

- app/scripts/apps/notes/form/controller.js
- app/scripts/apps/notes/form/views/formView.js
- app/scripts/collections/modules/notes.js
Fixes #493
"Wrong" means saved tags due to the auto save feature which saved the tags,
even if you were not finished writing them or deleted them afterwards. I fixed this by
creating the flag "saveTags", which is false when the note is auto saved
and true when it's really saved. So now tags are only saved when you
save the note on your own.
Thanks to @wwebfor for giving me a new way of seeing this problem and
thus making it much easier to solve for me.
> Don't save "wrong" tags anymore

- app/scripts/apps/settings/controller.js
When you press the save button in the settings you will now be automatically
redirected to the last page you visited. I implemented this, because it is also
like this when you edit a note. I think this should be common
practice among all the save buttons.
> Close the settings when save is pressed

- app/locales/de/translation.json
- app/locales/en/translation.json
- app/scripts/apps/notes/form/controller.js
When saving a note, check if the title is empty and, if yes, give it a default name ('New Note').
Fixes #540
> Handle empty title

- app/locales/de/translation.json
- app/locales/en/translation.json
- app/scripts/apps/notes/form/controller.js
- app/scripts/modules/fileDialog/views/dialog.js
Make the "Drop files here to upload" translatable and add a German and
English translation. Also delete a TODO Comment from an older commit.
> Add translation to drop file dialog + cleanup

- app/scripts/apps/settings/controller.js
It won't work when change some configs  as in `settings` page and
click the `save` button, the location redirects and window reloads
before the changed configs really saved.
> Fixed configs can't be saved.

- app/scripts/modules/codemirror/controller.js
Added a shortcut to indent a line or block in the editor. Also change
the indentUnit to 4, so that one indent will change the level of indent in
lists.
> Add shortcut to indent lines in editor

- README.md
Fixes #17
Adds the difficult installation of Git on Windows to README. I tried the
building of Laverna on Windows myself and this was the only part that
wasn't documented properly. Also changed terminal lines in README because
they don't work on Windows.
> Adds Git installation for Windows to README.md

- app/scripts/apps/navbar/show/template.html
- app/styles/core/header.less
**Changes**
- Created "General" label for categorizing the first five options in side bar.
-  Renamed header title from "Close" to "Menu"
-  Removed the hover  effect as well as button action event when clicking on a header title in the Navigation Bar. (It remains in the "menu icon") 
(1) I felt that adding another label kept everything consistent. "General" was the only name I could think of that best fits with each option but if someone else wants to suggest or change it, I'm all ears. 
(2 - 3)  With this change and the last one, I didn't like the feature of having the title and the icon next to it as a single button (I do think it would fit the mobile version due to the touch screen). Right now, I've only removed the button functionality of the Menu icon and the header title from the …
> NavBar: Changes in Header and NavBar Content

- electron.js
- package.json
https://github.com/sindresorhus/electron-context-menu
Otherwise the Electron app does nothing on right-click. This context menu plugin is convenient for right-clicking and copying links. It can also be customized in the future with additional menu items.
I tested that it doesn't do anything in the regular browser, only in Electron.
> Electron: Add electron-context-menu 0.6.0

- app/scripts/apps/navbar/show/template.html
- app/scripts/apps/navbar/show/view.js
- app/styles/theme-default/sidemenu.less
In response to issue #402  I've added drawing a tree to the navbar to show notebooks in a hierarchy.  The tree works up to any depth, and it always shows a corner pipe for the last child. However, there's no logic to wrap the tree if it gets too long, but this case is unlikely.  The other assumption I made is that the list of notebooks is ordered with children after their parents.  
It seems to work well.  Tree branch icons might look better than the pipe symbols and dashes that I'm using.  Here's a screenshot:
The first commit was a messy proof of concept and a lot of the logic was moved out of the template in the second commit.  Let me know if I should squash these and resubmit.
> Navbar show tree

- app/styles/theme-default/sidemenu.less
This is the best I'm willing to do right now. I couldn't manage to shrink the line height of the center pipes to actually connect them.  Maybe you can take a crack at it?  At least the dashes are centered with the pipe now.
I think we will need icons to make this work well on mobile.  I have not tested this on android (I'll do that when I figure out how to build the APK), but I would bet it doesn't look pretty.
> Improved line styles.

- README.md
It's time to move from `yaourt` to `pacaur` because `yaourt` don't have a clean build process.
> Edit Arch Linux section

- app/locales/locales.json
Lack of language string, although translate.json is available and ready to merge.
> Lack of string - Polish language

- app/scripts/modules/codemirror/controller.js
Ctrl-d conflicts with default browser behavior of "delete forward character".
> Change divider hotkey to not conflict with "delete"

- README.md
Singing on MacOS can remove the need to click something every time you open Laverna.app.
> Updated README.md to include directions for signing

- app/scripts/components/markdown/Markdown.js
Hi, initially I cloned this repo because I wanted to fix a UI bug in the released version where the title for the note is not shown, and instead the word **title** is shown. Then I realized that this bug was already fixed in `dev` branch and `dev` branch is way ahead of master.
But I found another bug during the setup, that is caused by the renaming of `jade` into `pug` in the `prismjs` package since `1.8.2`: 
- https://github.com/PrismJS/prism/pull/1201
- https://github.com/PrismJS/prism/blob/gh-pages/CHANGELOG.md#182-2017-10-19
This bug causes the web app to throw error and stop working due to missing dependency:
```
Error: Cannot find module './prism-jade.min.js'.
```
Ideally the change should not affect this project because the version of the `prismjs` package is defined as `1.7.0` in …
> [FIX] Rename jade to pug

- bower.json
With the last changes of device.js gulp build breaks.
> Use static version 0.2.7 of device.js

- app/locales/oc/translation.json
Used the masc. forme instead of fem. «unA nòta»
> Minor correction OC file
