Laverna/laverna

app/locales/de/translation.json~

Corrected three small typos in the german localisation.

Corrected typos in locales/de

---

package.json

Now using underscore version of Laverna itself.

Bugfix: Conflict with multiple underscore versions #274

---

README.md

Closes https://github.com/Laverna/laverna/issues/265

Note on removing grunt-phantomcss

---

app/scripts/main.js
bower.json
gulpfile.js
package.json

Seems like a some Continuous Integration could be helpful. Are you interested in help setting that up?
UPDATE: Added a couple resolutions to `bower.json`.

A few small build tweaks

---

app/scripts/apps/navbar/show/template.html
app/styles/core/header.less

The navbar title should fit in the space provided or be ellipsized.
addresses issue #305
I wasn't sure about naming conventions, but I tried to stay consistent with what I saw elsewhere.

:bug: fix the text overflow in drawer navbar title

---

electron.js

Bring back Cmd-Q to quit the application

---

app/config.xml
config.xml

change the minimum SDK version from 7 to 14

 Android PhoneGap doesn't build #367

---

app/locales/locales.json

Add Czech translation

---

app/locales/fr/translation.json

update fr translations from en

---

gulpfile.js

I was not able to run `gulp build` until making the change in this pull request.

Syntax error in gulpfile.js

---

bower.json

See issue [#1300](https://github.com/mathjax/MathJax/issues/1300) of MathJax and the corresponding issue in Laverna #409

Fixes artifacts in MathJax and Chrome

---

app/scripts/main.js
app/scripts/modules/markdown/libs/markdown-it.js
app/scripts/modules/markdown/workers/markdown.js
bower.json

This plugin allows specifying sizes for images. I hope it is useful for someone, it is for me and that's the reason I forked it.

Add markdown-it plugin markdown-it-imsize

---

app/locales/de/translation.json

Fix some typos in the German translation and add translation for new englisch words.

Update German translation

---

app/locales/de/translation.json

Der Import Button ist nicht gelb und der 'Weiter' Button heißt 'Nächste'.

Fehler beseitigt die beim ersten Aufruf erscheinen

---

app/locales/en/translation.json

Change description of Dropbox

---

app/scripts/apps/encryption/auth/controller.js
app/scripts/apps/encryption/auth/template.html
app/scripts/apps/encryption/auth/view.js

Fixes #520
As written in the issue there is a trigger when the password is wrong.
But it wasn't implemented in the view and the call had to be made by
self, not this. The method that is triggered now shakes the
button and clears the password form. The shake function was implemented
in this function because I didn't want to use the whole jQuery-UI
package just for this.

Show notification for wrong password

---

app/scripts/apps/encryption/auth/template.html
app/scripts/apps/encryption/auth/view.js

I shifted the style parameter from the HTML file to the JS file and slimmed
down the shake function.

Take out style parameter from HTML and clean up

---

app/locales/fr/translation.json

Update French local

---

README.md

This request resolves issue #545.I felt that @jlpoolen's suggestion should be implemented as it would be useful for those who are new to using Github and the command line.  As I mentioned to @jlpoolen, I think that some steps were left out (for example, forking the master repository) by the original author of this README file because it could be implied that most users of this product are developers and as such, are most likely familiar  with how to use Github, the command line, and other technologies mentioned in the documentation. Perhaps there should be a disclaimer either in the "Installation" section but before the "Desktop app installation" section, or towards the beginning of the file, that explains to people these expectations and maybe even some resources for those who are new to …

Added change directory instructions to README installation section

---

app/locales/de/translation.json
app/locales/en/translation.json
app/scripts/apps/notes/form/templates/form.html
app/scripts/modules/codemirror/controller.js
app/styles/core/editor.less

Add a display in the footer of the edit mode of notes to see on which
line you currently are and how many lines there are in the file. Also
add the German and English translation.

Add number of lines/current line display in footer

---

app/index.html
app/styles/theme-default/layout.less
app/styles/theme-default/loading-animation.less
app/styles/theme-default/main.less
app/styles/theme-default/variables.less

Update the loading screen so that it doesn't needs to be localized.

Create a new loading screen

---

app/scripts/apps/settings/show/templates/general.html
app/scripts/collections/configs.js
app/scripts/collections/modules/notes.js
app/scripts/collections/notes.js

Settings: Sort notes by Updated time

---

app/locales/de/translation.json
app/locales/en/translation.json
app/scripts/apps/settings/show/templates/general.html

Added and fixed the English and German translation to the 'spaces per indent', 'sort notebooks by' and 'sort notes by' options in the settings

Add and fix several translations in the settings

---

app/scripts/collections/notebooks.js

Sort: Fix notebooks name comparator

---

app/scripts/apps/settings/show/templates/general.html
app/scripts/collections/notes.js

Settings: Sort notes by title

---

README.md

The AUR package of Laverna can be found [here](https://aur.archlinux.org/packages/laverna/)
```bash
$ yaourt -S laverna
```

Edit README.md to add Arch Linux installation instructions

---

app/locales/da/translation.json

Also fixed some consistency issues.

Fix for grammatical and semantical errors in Danish locale.

---

app/locales/fr/translation.json

Updated french translation

---

app/locales/oc/translation.json

Some mistakes, it should be grammatically correct now.

Update OC language

---

app/styles/theme-default/prism.less

Added spacing to inline code within list

---

app/locales/en/translation.json

Change bellow to below.  Incident #885

Fix the typo in translation.json for english. Incident #885

---

app/styles/core/editor.less

I want to move or remove the editor footer.
⬇️

fix editor footer
